export const GET_JEWELRY = "GET_JEWELRY";
export const SEARCH_JEWELRY = "SEARCH_JEWELRY";
export const SET_ROUTE = "SET_ROUTE";
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE'
export const SET_CATEGORY = 'SET_CATEGORY'